### ISSUE TITLE
Sample Config

### ISSUE THREAD

**Issue by Maenshae** [thexmanxyz/network-share-reconnecter#1]
It would be really nice to have a sample configuration for the variables in share_reconnect.vbs.

Since i never were in contact with VB before, i would have to look up, how to assign values to the variables and what type is expected (string, int, etc).

**Comment by thexmanxyz** [comment]
@Maenshae I'm not sure what you mean. Because there is a sample configuration in the `vbs` file. Maybe you took an older version because in the latest version there is a very clear configuration. It's also not necessary to assign any variable. You just have to modify the prefilled function parameters.

Please take a look at the [Function Call(s)](https://github.com/thexmanxyz/network-share-reconnecter/blob/master/src/share_reconnect.vbs#L41-L43) at L41-L43

[Latest Version v1.2.2 (updated)](https://github.com/thexmanxyz/network-share-reconnecter/releases/download/v1.2.2/nsr.v1.2.2.zip)

So I'm not sure what you mean. Please let me know if this solved the issue ;)

**Comment by thexmanxyz** [comment]
@Maenshae I reordered the script to present the server-/script sample configuration in the first few lines of the file. Instead of at the end. That should make it clearer in the future.

closed

**Comment by Maenshae** [comment]
Thanks for your help Andreas,
i didnt notice the sample config at the files end, got it to work now. 
Sorry for the fuzz!

**Comment by thexmanxyz** [comment]
@Maenshae Nevermind, it was a good note because I didn't mind that placing the config at the end is a bit confusing ;). I'm glad that it works now!

**Comment by TMDaines** [comment]
I can't get this to work. Pretty sure it may be a user error.

Does this look correct? Or have I got speech marks or anything else messing this up?

Set srvCfg1 = createSrvConfig("192.168.1.12", Array("\\NAS\MyShare"), Array("E:"), "yes")

**Comment by thexmanxyz** [comment]
@TMDaines Yes it may be. However try the following and please report back:

```
Set srvCfg1 = createSrvConfig("192.168.1.12", Array("NAS\MyShare"), Array("E:"), "yes")
srvConfigs = Array(srvCfg1) 
```

Is `NAS` part of the share path? If yes leave it in the path otherwise remove it. I can't say if this is a hostname or a folder. But I assume it's the leading `\` in the share path. Remove it and it should work.

If `NAS` is the hostname try `Array("MyShare")` only. You can also test the script by enabling the debug modus and simply executing the script with double click. If it reports your server as online back it should also work with the scheduler.

**Comment by TMDaines** [comment]
NAS was the hostname, if my understanding of the terminology is correct. Removing the double backwards slash before it has seemingly resolved the issue and made the script work.

[For some reason when I copied the line from my script to here, it has replaced the backwards slashes with forward ones and changed the double backwards slash to a single forward.]

**Comment by thexmanxyz** [comment]
@TMDaines 

It's possible that the slashes are somehow changed here because of character escaping. I'm glad to hear that it now works. However as general information:

- Only specify either IP address or hostname (the human readable name assigned to the network device)
- DO NOT specify the hostname or IP in the `sharePaths` parameter
- UNC paths have to be specified with backslashes and in the current version (**v1.2.5**) of the script DO NOT use leading backslash or leading double backslash.

So generally DO NOT use such lines 

`createSrvConfig("192.168.1.12", Array("\\NAS\MyShare"), Array("E:"), "yes")`
`createSrvConfig("192.168.1.12", Array("\NAS\MyShare"), Array("E:"), "yes")`

However I already prepared a commit which corrects such paths if not specified correctly, so that the script by itself changes wrong passings and provides better failover. But as a general rule, if you access your network drive under Windows with `\\MyNASHostname\path\to\share`. The corresponding script line should look like this:

`createSrvConfig("MyNASHostname", Array("path\to\share"), Array("E:"), "yes")`

For an UNC path which contains an IP it works the same e.g. `\\192.168.1.12\path\to\share` would require the following configuration

`createSrvConfig("192.168.1.12", Array("path\to\share"), Array("E:"), "yes")`

This post is also intended for future readers to be clear on how to specify paths. The parameters were chosen this way to allow multiple share paths per server configuration without doubling hostname or IP.
