### ISSUE TITLE
Black screen for minutes and very slow boot/logon

### ISSUE THREAD

**Issue by backamblock** [thexmanxyz/network-share-reconnecter#10]
Edit.. oh well.. ofc i only changed the file path to the script.. not the "Start in (optional)".
My VM does not have a D: drive so it couldnt find the folder.. 
everything works as expected..
i feel so stupid right now.. -.- xD

**Comment by thexmanxyz** [comment]
@backamblock Hey, lets see if we can solve the issue but I'm pretty sure we can. I would recommend to execute the script manually first and then report back. You should also enable the `debug` parameter in the script file and check what the output is. However if the preparing screen is what I have in mind I'm pretty sure it doesn't relate to the script. Because typically it won't be executed at that stage on bootup. If you used the default scheduler task file 

```
    <LogonTrigger>
      <Enabled>true</Enabled>
      <Delay>PT15S</Delay>
    </LogonTrigger>
```

The execution trigger is delayed by 15 seconds. So it won't even be triggered until you are seeing desktop except you have a terrible slow machine.

Additionally, ping has to be supported by your machine `Bootnas` or you have to disable the ping support of the script. Otherwise you won't get the desired results. 

Your configuration looks fine, as far as I see. It also points to `\\10.0.0.1\Botnas` which you indicated in the comment below the config. However I have to say that I never tried the script on LTSB 2016 but it should basically work. But let's see try what I have written and report back.

**Comment by thexmanxyz** [comment]
So my comment was useless because I already wrote it :D nevermind! I'm glad that it works and you got it running.

**Comment by backamblock** [comment]
Wow, that is a quick answer :D 
Sorry for the time haha

**Comment by thexmanxyz** [comment]
> 
> 
> Wow, that is a quick answer :D
> Sorry for the time haha

I saw it right in the moment you posted it in my mail because I'm getting rid of email backlog :P.

> 
> 
> Edit.. oh well.. ofc i only changed the file path to the script.. not the "Start in (optional)".
> My VM does not have a D: drive so it couldnt find the folder..
> everything works as expected..
> i feel so stupid right now.. -.- xD

Don't be too harsh because things like that can always happen nothing to worry about :P

**Comment by thexmanxyz** [comment]
> 
> 
> Wow, that is a quick answer :D
> Sorry for the time haha

I saw it right in the moment you posted it in my mail because I'm getting rid of email backlog :P.

> 
> 
> Edit.. oh well.. ofc i only changed the file path to the script.. not the "Start in (optional)".
> My VM does not have a D: drive so it couldnt find the folder..
> everything works as expected..
> i feel so stupid right now.. -.- xD

Don't be too harsh because things like that can always happen nothing to worry about :P

**Comment by thexmanxyz** [comment]
@backamblock 

> 
> 
> Wow, that is a quick answer :D
> Sorry for the time haha

I saw it right in the moment you posted it in my mail because I'm getting rid of email backlog :P.

> 
> 
> Edit.. oh well.. ofc i only changed the file path to the script.. not the "Start in (optional)".
> My VM does not have a D: drive so it couldnt find the folder..
> everything works as expected..
> i feel so stupid right now.. -.- xD

Don't be too harsh because things like that can always happen nothing to worry about :P
