### ISSUE TITLE
Add support for whitespaces in share names

### ISSUE THREAD

**Issue by max06** [thexmanxyz/network-share-reconnecter#2]
Hi there!

Great tool you wrote there. I just reinstalled my windows machine with the FCU and found my network shares being disconnected until I interacted with them in the windows explorer - which is not good. Fortunately, your solution steps in here.

The only problem: I have a network share containing a whitespace. `net use`-Output for example:
`OK           N:        \\DATENGRAB\TV Shows      Microsoft Windows Network`

Any idea how to add a share like this? Might wanna extend the script by some `""` in there?

Thank you :)

**Comment by max06** [comment]
Already solved it...

```
Function getNetUseCmd(srvConfig, pos)
	getNetUseCmd = "net use " & srvConfig.shareLetters(pos) & " ""\\" & srvConfig.hostname _ 
				   & "\" & srvConfig.sharePaths(pos) & """ /persistent:" & srvConfig.netUsePersistent
End Function
```

I added some double-doublequotes in there around the UNC-Path, which did the trick for me.

**Comment by thexmanxyz** [comment]
@max06 Thanks for pointing on this. I will update this in the code base. didn't think on whitespaces because i only need it for administrative shares :D.

**Comment by thexmanxyz** [comment]
@max06 I fixed the problem in the code base and also created a new release [v1.2.5](https://github.com/thexmanxyz/network-share-reconnecter/releases/tag/v1.2.5). Thanks for your words I really appreciate them and I'm also happy that the script helped you with the reconnection problem :).

/closed

Edit: Link changed to v1.2.5 because I noticed another bug ;)
