### ISSUE TITLE
Doesn't work with WebDAV Server?

### ISSUE THREAD

**Issue by mvevitsis** [thexmanxyz/network-share-reconnecter#4]
I am trying to auto-reconnect to my Kolab server.
When connecting through explorer I specify the path as 
https://apps.kolabnow.com/files 
and type in my username and password; it connects fine. 
Maps as K: with the custom name Kolab Now

I have it set like this: 
Set srvCfg1 = createUriSrvConfig("apps.kolabnow.com", Array("/files"), Array("K:"), "yes", "username", "password", true)

But when I run the script, it doesn't connect.

**Comment by thexmanxyz** [comment]
@Matvei27 Hey there I think I already see the issue you are facing. Can you please try the following and modify one line in the original script and check if after that modification the script works for you. This would be **no permanent fix** but it would help me to verify if it works for you in this case. If it works I will adapt the script in a way that prevents the occurence of the issue.

As a small background information: kolabnow.com does not allow to ping it's endpoint so therefore the `net use` comand will never be executed and therefore no connection is established. That's probably what you experience.

However here is the fix. Replace the Line 459 (`retryPingServer = offline`), please see the link attached to verify which line is meant [replacement point](https://github.com/thexmanxyz/network-share-reconnecter/blob/master/src/share_reconnect.vbs#L459), with `retryPingServer = false`

Please report back, thanks!

**Comment by slopsommelier** [comment]
Yes, I can confirm that this fixes it. Now double clicking the script mounts the drive as normal.

**Comment by thexmanxyz** [comment]
@Matvei27 Glad to hear that this fixes the issue, so I was right on that point. Give me a bit of time, I will integrate a new config value which allows to take better control over the global ping configuration. So that this special case is covered. I will report here back as soon as I'm done and how you can configure the new version so that it will work for you. I think it will take me about 1h. See you soon ;)

**Comment by thexmanxyz** [comment]
@Matvei27 New release [v1.3.4](https://github.com/thexmanxyz/network-share-reconnecter/releases/download/v1.3.4/nsr.v1.3.4.zip) is here which contains the fix for your issue.

In your case you only have to configure the parameter `pingDefaultSrv` at [Line 74](https://github.com/thexmanxyz/network-share-reconnecter/blob/master/src/share_reconnect.vbs#L74) and set it to `true`. Thanks for your contribution!

/closed
